### ISSUE TITLE
Everything is upsidedown

### ISSUE THREAD

**Issue by yeSpud** [jeffrypig23/Mayterm#6]
If the style sheet is removed everything is upside down

🙃

**Comment by yeSpud** [comment]
I'm just going to call this a feature and move on

**Comment by averycblack** [comment]
That's not the right way to solve an issue 🤔 :P

**Comment by yeSpud** [comment]
Technically [a fix is being worked on](https://github.com/yeSpud/Visualizer-framework). Albeit  indirect as it's essentially a full rewrite of the entire project, as it's being split in 2
